name: mentora
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flutter_svg: ^2.1.0
  table_calendar: ^3.1.2
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  shared_preferences: ^2.5.3
  http: ^1.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  uuid: ^3.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/signup.svg
    - assets/images/reset.svg
    - assets/images/instructor.svg
    - assets/images/student.svg
    - assets/images/logo.png
    - assets/images/default_avatar.svg
    - assets/images/default_avatar.png
    - assets/images/splash.png
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"